### ISSUE TITLE
harbor.yaml

### ISSUE THREAD

**Issue by MoSehsah** [gorkemozlu/tanzu-gitops#2]
update in airgap.sh 
to add additional sed to replace the following 
```
        url: projects.registry.vmware.com/tkg/tkg-extensions-templates:v1.3.1_vmware.1
``` 
in harbor.yaml

**Comment by MoSehsah** [comment]
also for fluentbit

**Comment by gorkemozlu** [comment]
thanks. fixed with that commit: https://github.com/gorkemozlu/tanzu-gitops/commit/d9317da3780ba3b76960d13dec0f925aec6c2830
